version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=topblog
      - POSTGRES_PASSWORD=topblog
      - POSTGRES_DB=topblog
    ports:
      - "6432:5432"
    restart: unless-stopped